version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://webshop_user:yourpassword@db/webshop

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshop_user
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
